server:
  port: 8085
  servlet:
     context-path: /hair

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/haircut?useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
